### ISSUE TITLE
segfault from C stack overflow

### ISSUE THREAD

**Issue by nicolettacommins** [gtonkinhill/fastbaps#14]
I'm having an issue with the very first step reading in my fasta file using import_fasta_sparse_nt(). I'm getting the error:

Segfault from C stack overflow

My input fasta has ~350 sequences and ~700,000 SNPs. I tried inputting a smaller fasta with only the first 2 lines of my fasta, but got the same error.

**Comment by gtonkinhill** [comment]
Hi,

This is probably due to the very large number of SNPs in your alignment. The fasta load function was written for speed and optimised for slightly shorter alignments. A work around is to use the `ape` function `read.FASTA` and pass this to the fastbaps import function as

```
msa <- ape::read.FASTA('/path/to/msa.fasta')
sparse.data <- fastbaps::import_fasta_sparse_nt(msa)
```

If your alignment includes non-varying sites I would also recommend first running [snp-sites](https://github.com/sanger-pathogens/snp-sites).
