### ISSUE TITLE
Inconsistencies with phylogeny

### ISSUE THREAD

**Issue by luciagrami** [gtonkinhill/fastbaps#19]
Hello, 
I obtained similar results to those presented in Tokin-Hill et al, 2019 for Neisseria meningitidis, but they were even more dramatic.
A group containing many taxa from different clades is generated. 

![f2](https://user-images.githubusercontent.com/17276595/184975892-610feb5a-933f-4dc3-a8b9-09d4cf36a01e.png)

My input data consists of a SNP alignment of the core genome, and I used a symmetric prior.
Additionally, I examined stability using boot_fast_baps (groups are well supported), and compared BAPS results with different phylogenetic reconstructions, but the inconsistencies remain.
The results are similar using rhierbaps, at the first level, at the second level the groups are more consistent with the phylogeny but too many for further analysis.

The reason behind this clustering is biological, or am I missing something about the procedure?

**Comment by gtonkinhill** [comment]
Hi,

This might be due to high levels of recombination. In these cases the phylogeny might not be very accurate. The large cluster that is spread across the phylogeny usually represents the genetic background. That is, these genomes do not group into more distinct smaller clusters.

If you are confident in your phylogeny it is possible to force fastbaps to be consistent by using the `best_baps_partition` function and parsing it your tree. This is outlined towards the end of the Readme.

**Comment by luciagrami** [comment]
Great thanks!
